---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: whatsapp-bot-secrets
  namespace: zumba-staging
spec:
  encryptedData:
    GEMINI_API_KEY: AgCebVt041glihxCMpDSLgMdlSP+M/ItMnGJZIwBtncLbhkJDmg55fvvHNDsPwcbxMQVTJCTg7djMgh+tdMGFPObnEnOUzpHgslvgpmmv79Z32tizxM7CDXhYhidlMWaIPEAXwVJwA6KQp6jpDEAPNwETxBw+G3CMJpYuttcdHhfP18pWfTVmBfQtslZ572gdJy4dUGV+zBq71LhwafloGiR3VyM8mcO8FIgUp2UEwYR4Rhxw4HIyeiBJOYMyINcls1zjHK0j57HIssjSQHNFtY9bGpHNvktXFux+1SSnLn7DszGCjF9XwhPm6CgwaVlXAvZ8G+xfuFIlM96c4/YmWGJy6WIM9gmRy5BxI02l0yKB9T3D0TYynNap9noPv+UxkuS8/nHSHhhEg/tncz+tPQ8xKiIztEbm/YJtxpFt1ujGjSoM34qqqs/QUqwzk3YNR0U9zdm9FEgpPSreb8s3U+L9dM4Smu4FneX183JEsgWlOR9ZAQEnog9SINwEdiimBzNIwCDTYgUCcjjA9fyy6GLHt+3+3Dq+l20Szze7L2yJqoKw7A6/Q7HcbEWw2vv2S50vC9UJVz+ssRAt4s4msvXYzQA++9cMPpwi7EqdCDUECilKEpcK0RrmvbDPDLMkXIWSAMgr08xb0Csqmr7dvSxSqrDblzpxKbP1myUZpfW9X6Bo17zoKnYRDGu5lbWPWTfhsIH1CxmbT25eVZRrE6adjrqPabAKVQanGsAsPC4B3U7rZR2eDU=
  template:
    metadata:
      name: whatsapp-bot-secrets
      namespace: zumba-staging
