---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-ui-secrets
  namespace: zumba-staging
spec:
  encryptedData:
    ADMIN_PASSWORD: AgBHuDQl8BPvShXWkwhDvrk15Q0DnvOweAQPR6KS0rYyxt6JNINkNLzSbiqTJ+cOEI+DQsIVYnP54zT0HBgQhgIn2i9Ifuwk3PIHDVM4wXHyc5hdvluCUVpjY/uT5rWdSlAVM6afebsQnXt/rXLnZIaShZCbpr19R4lihRKEvi51rl9C8EDIsfgmDMWdDlZioh5Z8qZLCJNOaP1Ph+Led8uapD4rQjcM6mXZHNmDSDbz5q74w32cAQKay2JH1VVk2gGHcY4Ud8ErOElgTHswcOizbksjGW1hoeXVpOLa/qhUBx1+3fSbvulh1Vj6A3vrWwIpYS5oNHX34E01gVu5CJzqBqU3Q3x1nIHrzj6k+4FkbZMsEs8IVIpkVjTZNtZXiAWgPbxJQWr6ujZKcWltmIzWMNrN81pUyQBz2L6jnJOdC4iE5Zvvw629lPJegFUjk3pNtvB2QqJHl9o3XY7s9rG5CnaOTsKFHUFOBjk1axH6kL0GPYUCKPTusRbPvEOx/ntyXitcfs6cN7DhaJ2lsnegGm3SJzY+scSM6sJIBBZQrEyneU6+fnWtIjPUjjBvbyicGeZE8ph7HW0ngRyxIw4aXoyYR/pS346+t/VqsSdyEQxa7Ba2DhNTvQi+l+x7uF6YC5FIN3MQGVF+UR3663NwOUu93C4CTuIoB77WeEk24diaS/4A7tkuUH9uiWmbt+fBv3FpWyNEGeMs56a2byTXfr/7jDNjIOhsL2fIhRVLqMfb6fw=
    SESSION_SECRET: AgC0+vdjlRiQk/fN7SX46zYnIhJN8UaA7oFxElO3ylmFJVkhTKKwO5L72EoV+/zVLORVWBQ2/dMlh7jK7sh19PWqfvygkuedFGF4cPrGm3fn7yeFz0otsYwXTUD6lzSaoBkSNVU07hYu811NMziAGntiwNnGjPI39ygUS8jlcKX2PkS4fOVo7NCBYV9hy4NodtevjqN88cMTXMPZoL0z1VKYhmfsf0posofKfZ0pNm8/WFI96LGg6qzh6F/XxJMq8M3RpBD1EKra9XBfUze8B+Mzyj8emoid2SIVRrcRQ/jm5NltsSECDrXXrsD/ZrTt7biHoK+fJnH3BCTKY/022l28HNj8073stcxF1qjwXxA5278+P5B4czjtZuq8p8s2OQ8KfbFBlmCQu5CPkMtUVKE1YvlWtwPNJaIOfskLjiTdrCtLJp/fye0VMEq8EDOyasPj5qtD1TXaBQWg4LY948Vxpq1YVQoYjcLSPFd+W5jLOeIkw0zt8RjAOmd9I9je9FpbG83fgWXcX9r6Hvxq2GfSVSAXWdwW5KAFvd5H7577ea2DX5LpZfkx3ZsZwzR24b0uXLloNlPGvMxoCej1U0iB1Txb+okZMdnIG01KL1fR/Y5PL1R1DaLJdMQrwOtUjaJrGpvrVU3zWce9kUDTtiVH0LHVej7COBWuQOgE66SvJDshrBFxhU87vCgsYMo5e/ivpE7G7Yi8jsKlKw/cjQVYFqOia1FhrrLiotzywHJCDnQjPhFAitAp1HYSrQ==
  template:
    metadata:
      name: admin-ui-secrets
      namespace: zumba-staging
