---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-ui-secrets
  namespace: zumba-staging
spec:
  encryptedData:
    ADMIN_PASSWORD: AgAfktd14PIWatU9VkJEJ153/2xStNjo9RMvYVoovh6zXC/z9rj1BZ2hiQIfbYESfcWYb7sBqpP4Qa/8yj8ai2G47OLxLpOOD8IMqzVQrap8L9p3xbsYznRNHM6ihSto14qmBAPk1w4pZU3t8wl3u7E5kfX6ItTtNtFb7LT1Xm6AjUjUfZ3/STFOLiCVKcKf3CzzN67s5flYZf1F9mnSvoyjKedTk/wUgrhWpUg3i/dLb/oISBZzYd3F1zJwNUM0O4d9G7fNmPjzt2176a2H+y6vSzpbNy6pnv7UtbcQVU4Gy1sWhj+fSitstjXsECxXcvN4LFp8xciBlQ74DJ9Sn2rpQxK5uwfX9x9SZ1Q2lm5aOdMCmqAoQht96Ugsi+6pSbH48NdjUcqc9twc96OxdjxjNm4H9Spo1rkh1+zW4pxADkbuIHE6tf0YK8jUoLtr2x1hDXxeQFn4q1pgBJfz0kjvTFnE+31AlNEBUh+w1wUS50NTXnBW2uw0D06JSMH4Zllb9w6oXn9CPKENKaDlL3sLYP6MP+EeEvvzb80jx779MAT/hcXRnbX4q9YmdaGirWs4V/mAN9rfpMsBVsnU8/Zwu51Ttg59GIahu6i/f4KsMFEiYTbOOWb9Q4gRG7NpKQcOGRoAIrm4kER0xLqWSOQUusrSfbL4JXDM07rNNqICaxHjdQNLR5X0xjhlrQXd+LKvLrK/LoLZdReCM1UMB3ANReUtOHb5sdwuL8CdFvbl6D++Xbc=
    SESSION_SECRET: AgDovzvCWJR5+4/WbbyAYUKKc/JJb+3KdZDJDGurt/rv80DCgyVBZa2MC1JJuYuX8oUT9s7E/pTKOWIqo9W2t5RAP1rbl7WIJZ+eD6AkBSgkFH0iw37fVX5PI9LVARMetfWeLB0nosqyhE0J9Bmsgzz3i1pQgp9OsBUd8vOv9vCvy1EOHzpabP46TJxFnQbvMzGDPtROPCQMI1gGIAPR2PgoVLT+3O9q3QEE3vzHxICS3jdBOIyAfGeEtYv80TeoiwttW/71wuoKgsZ4xHw09waMbfMEXNKGqxjHBQ/iedxxS8PvAMVcZJH9KGhN4JH0bvq8o0kk26Ja7T+aDJ91ZaC15POHSWBX3j0iBj42bkyGtoFkPbiLunzwNgcWRsVbXcs+yuRL4GazvQUrzO6F8HxCz8JXEYdkdVm5y+w6huBwfon4GfvPfQ8to2xcfgheQjJacDxbIexHEdQTFGIx/3/EL624UEnZLkh6BrqyzUyAQYPFXgCbwdQ56gXz02O98g35u5tgto5It1ss2ws8bCUv7WfYht6XBMisKwcRiOukofPUoXV/vJStVTd0wdWcrguoi3VlgE96yPOv7fp9w9OiqDzqFGdeKk51oAxsV7IUdxePs7V1bx8luRf6Xo17U2JJdcCFy0MZ+nRmtIW06fudtUnMNl0ItqxteLsVpSk/ybdt7+zxeAP3Dyene/nKF4Bqmv/ROW2mUZ9axE9mb0OkWq4mj5OEjksIzuD6APKHYQXODo/re8SkURwoOw==
  template:
    metadata:
      name: admin-ui-secrets
      namespace: zumba-staging
