---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: evolution-api-secrets
  namespace: zumba-staging
spec:
  encryptedData:
    AUTHENTICATION_API_KEY: AgDlxEeZikBMqZN39FWYcd/23NfmXedPTLLWvaCfbPM+qsj5HUG/FwQPaQWYSsudRVk9vdxNWF21yqBXjVfwpcE5Ie8aEyv/ToWnPm/GrfivOyYxxXzMVc9mO6/KAOhTHFZlf16XSn20v1l/ztzmtojUl2YCJmD9ZLPrlullyrlwxXaI7k1uodjUoxo7gGsG0V+/H8Vp7UfsU1m8Mhlv4jkoBRTSZrEjcY37txgN6YHKXAlkGHG+D4ykPQ1kF33ge9B0ai06inN78FPODpq+EHsPPQ7joTXrZQ4BimGZ4dYJvaYBLKGxN78zpcBV8LtQHz0QGMaM+peK3WsN3SMPGcoDqbkUqByewv/DLat8500i5JAMNepeKZn4EXImF5u0AJeGeqYMpG3uHBOSFZjkausX6gvKGA24FACpssfVbr5BNIwWmJj9X+1aaoP7BJfyF/aRMmgUzF8FTBuVTFOv5oIwGpAFTpLvYz0MCki94BL4qPsBhIfQimneknGMQikNkzicm9eFNR4k3RJ0JhV1namTvVlv8fIQRWoMZdqeeJ8vLpJoCfZIxXiwnY/W/XX+C6SdkjHp+q6u+AydGz9eFvC5kkcTytAabZyXmdealIKCo5HSKKkXMdxdu1LM9CvYXdTSw3iIjjCCUQpAjFxGamA8ECgoGG8op6PftZ+/RgHiIQuSRVAJeCchDvjKJlOQzT3ixb1TUvBG5FG8Ovoqz3yl2kDGMVpctKAxDKqWO6bF8VgEora9scxb0a8xCI3sRR4=
  template:
    metadata:
      name: evolution-api-secrets
      namespace: zumba-staging
