---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: evolution-api-secrets
  namespace: zumba-staging
spec:
  encryptedData:
    AUTHENTICATION_API_KEY: AgClwZ/QmMzN8TEJHx+xTgsMt51zIrqZzPTPRUz4w2VysF//yluxhT3ryVLujdX/xz+pH7dmBo0t9gZ+hxzdLzneppVioq8lyWNIecJagmyfkmHTb8o6rk4hrnlwPaN6fsaA4Nj3y/DuY4XnRvscsHffB42kIZ10aazajqiUdt0NhMLkbrh+sNBZtG5FHCBSyfH8XzaxtfkUxZa6JmITEA0I30HNx0Xx/pWQF35YLNw72/BPZpJ6Z3/iQaXWwGp6IQ/VIAQBa8Kg0nAHBnb2z2e1sc5Kd13wGxErg4Zzcp7JUWLI47mf8cNFTCIvnHhfb1d7Z+MCfV5TT6R4yQmXZMelsW//iVUPvzJ+f8C2jUDfBgDpoZ5/37IPVJUYxUauM+ApFWXqgDVuDKZtgYYjdISyeqN80iBWNgy85wZU4o/cRNynm4Dnn0/apIbgenkzLp68RPQSU8SC9Vq7jITf2dcnvvB+P74FKj2THo6t6vELGF5Cx+XgTFT3CkqdF10TkCltXYV2xEIV2qhSx8i/hTnVCczooRYzzfQ+bRQ3FzakR/oGE5LV0KNms3oyHQU35PyeEjiB+IQZ0fmhNWxbFnrGrenaIJOFqUHBrMf4RlpfPiJC+QOOlv/nNEKEgEJ0kIa7YXJdULJ0IcTNyxBLrnTjUIeidr/jeBn+PbF6+Nus+sEoeUbI/EYu9/ENL/NipS4iwQUHuoB82mc46+JeaJusfQZKKyRw7j+BupM8cuWR46ftSCeVDmo9JMvXX/cXtxQ=
  template:
    metadata:
      name: evolution-api-secrets
      namespace: zumba-staging
