---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secrets
  namespace: zumba-staging
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgCC0bgKoZ4GBcyhzNMC7DJD9HyLevh3fGyrenYpweHNlIrlzm/Su/wVzRyE2TC7Fl3717PtTaAS8pP9eMNgE1qDIh3o/ZhFX6oV+9Rgp9n++PCAIZ1cmK979csyNoUsybX3AhHwxUmcmELzJZGknoghADAQkGZx1LfwAOBJoi56/UUlwo6tTdg5oID7QbQPHw3kOB/IGkXzXwEuFZfkFvG7JC+/Rms0XizU1dBuia/aakmSADW1QzwgQXMelvjVVn+eJ+xuJU7Z7wi1kDocjB69YZpH/ehyivh3rXtVHZ4vxMaIUtgXBlruQ/QLsk0pK1hRBNEU3i2Bq1fHdKj61IjSNoLe/1h5Hiz2eoIF0P+EUKsaoEPEXfx87dC8/HsGNmy1Lqc8aN2k6uIQcqMwM1xMDVzLTVpT8r/A6YoiZ94i5HVtxBFUgJFwh31Tf/dOa54GtPFXISI1QZcDM43n3EcWmcp0LOnzVe5Pqlit2MBxyi6NDQ1HspypsODzj00wfpf4A+MY58NPRe3qeo6ssVm54vneCKu9igjFQpKshB68uKtGLd4AG6sqJCBX2NL64GmQm/rDwd7OetRm4bnLaSsWsTbiGhg0kvoPGH6vCZ6rxtxDB69Kh7sPgyN63n69VqdAcgqs/xbtK5sxdRj1pw9Nnppseoy4eOAna1uf/suDSA4jqdjBY0WUjAs0pDABj2V4b3idunTS2DpboQeizyhD4hVgf9f9tFuOG1a150xE7g==
  template:
    metadata:
      name: n8n-secrets
      namespace: zumba-staging
