---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ngrok-secrets
  namespace: zumba-staging
spec:
  encryptedData:
    NGROK_AUTHTOKEN: AgCt+Dy4Lhm+SjWdqhwa95qVJoLTWC2ZMeJMRmBAGo6FeY0ak07jPNcIIipnh8iOoHYgaUupfC80ymLLeFvbkJUvMfx+k0jV86QI9hnMFcIQp7AwjKqVhDJM0Uny4yPFJ/tBZEnB3SI1uopk6SxFrNDJlYYOkJPwDSTUdZriokIIcUCRtJNCNQfOjX1JuBvWECFgt9uNrPt2qSi0LptZj6cr2Q0IRJt7LidUhPSvSPbiTAoAEFpd+H6qLopIvYw+qukGARYVXsTrcwmfWxM3uS8G2WXJvtyqrZ+G25YTMAa2Z/T6AJga4WX7oFkEYaZhF7TvEuLB1WS68HRRuFO4liRrzisz/llelGMCYHALVTFN+35WGb9HVMsY33jON20GEphdi/FovvrltLc9ZI0rcTmSxaSdwxOaGW5zJKu2GBYIZGNa3lLMRwwlCEeIcugmRX9AIV3XbKbKEqPVWbYNXn3AzyHoxo9SpwjBegd9epJyf1har/jh48Fd5XRIMTY2fYfVZXLCsh7BcsBxer+tMkEvJBxFc2tbNwfLsnFyEPpfFOpO29LIsRvsMJ8QAJqLqrvxV6b77kD9jwJOV3H9OI/DUm01D5H6TDl9v1YqsipvSUOtr8LC5zatjty8gih7rjN6xnys+eDy+PzyQS9VSns61LciRkZ7aBcVyeCFLe9zDzvZSVFwve4IuIbwbf5aPjQimvayIWghn79wPPK3NscQyQAXj6izbdIGhLwbCETQF9SPWxSz4dC13bdbIvWt0ZdW
  template:
    metadata:
      name: ngrok-secrets
      namespace: zumba-staging
