---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ngrok-secrets
  namespace: zumba-staging
spec:
  encryptedData:
    NGROK_AUTHTOKEN: AgDw0m2BBioSZgATJdv1JmOFWmxQ5bA1AgvbAMtNjq5rc/dDA9TUyoc9hlaZhdqJs5PDGBpqGP/KHu9khhZRYUqeKa8hGsvDYoB3DnOJ0VnrIy+yjDxBKvU9KbMi3ha2VruLVvcZ/UBMg5ppAOnhrg1r2qwLuncv+3DDIc6wwduE2O3V0Z7hFXg6OgdLrxcVgcZ6UZO7rhPmMsPlKssD1ksb0uOWbWnRbfhdmmUjqAJFzAZbBM/xNoRwPSLFmGlO06yRK65G9SDz4P27Lt/Cp6JEZCWpjRr+M6IYsKFuvuICNzjaohozSvo5SwnJx/dJFnFYqSpdNqYM/y2G2YFv6iGbA4YwFUMAGuk1lBMMPFBIqDtHOTS0njMY1w3u5fxPsXLX59UQoh0gEVrlnB5XpiMkDszwmIueUj4mnGYgsxQJ9X7CJV/UnoPP66drk7YhJRISLolg1v+leaOZNjedKh3tqGrqYN7QWUpdtInuUAUaPrAecI7UmN71LFbHTeOULipa4R+vLSocu/XkoJP9pmYhM7I1G3NbBzBBnKZmNTVyMrXdwrm1wlVsoYunhdFeWda66zITq6K+0Ybf9+EWtbVOELaM7juO2geW1Owka8eHJuMXg2yQxaPi1L8bdrhOS0AixqZC+uSda0pVbBwXTF5vxlmsfNRSSvihLXglpbE4jlsZlEKRdRoKtvTxns68pTL/gWD2LU2yRNG9IAN3hgB9e805OLS7gclf3c544vN7CPPdUAgLgy9p3vtpalSCuReO
  template:
    metadata:
      name: ngrok-secrets
      namespace: zumba-staging
