apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zumba.fullname" . }}-postgres-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "zumba.postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
